version: '3.8'

services:
  ouiwine-typescript:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: ouiwine-typescript-prod
    ports:
      - "80:3000"  # Porta 80 externa → 3000 interna
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=ouiwine-typescript-secret-2025-production
      - PORT=3000
    volumes:
      # Volume para dados persistentes do SQLite
      - ouiwine_typescript_data:/app/data
      # Volume para banco de dados SQLite
      - ouiwine_typescript_db:/app
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - ouiwine_typescript_network
    # Configurações de segurança para produção
    security_opt:
      - no-new-privileges:true
    read_only: false  # SQLite precisa escrever
    tmpfs:
      - /tmp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Labels para identificação
    labels:
      - "ouiwine.version=2.0.0-typescript"
      - "ouiwine.env=production"
      - "ouiwine.backend=typescript"

volumes:
  ouiwine_typescript_data:
    driver: local
    labels:
      - "ouiwine.data=sqlite-data"
  ouiwine_typescript_db:
    driver: local
    labels:
      - "ouiwine.data=sqlite-database"

networks:
  ouiwine_typescript_network:
    driver: bridge
    labels:
      - "ouiwine.network=typescript-backend"